# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

DomainMangaerRoot:
    resource: "@SaidulDomainManagementBundle/Controller/DomainController.php"
    type: annotation 
    prefix:   /